# Generated by Django 4.2.1 on 2023-05-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parties', models.ManyToManyField(related_name='movies', to='students.party')),
            ],
        ),
    ]
